### PR TITLE
Update readme typos

### PR DESCRIPTION
**Pull request by johnjacobkenny**

### CODE REVIEW

**Comment by johnjacobkenny** [comment]
Would be happy to pitch in if any low hanging fruit is available. I'm early in my career with javascript and frontend learning :smile:  Eager to learn more and give back to the community too :smiley:

**Comment by taion** [comment]
thanks for this PR! sorry, though – it looks like #25 beat you to it, heh.

if you're looking for something a bit more involved, it might be interesting to move the current karma setup here into a separate example; if you're familiar with how to package this sort of thing up

**Comment by johnjacobkenny** [comment]
That sounds great! Could you help me understand what are the important features that should be there for that example?

**Comment by johnjacobkenny** [comment]
I did some reading, just want to outline my thoughts.

- create an empty project
- initialize deps (karma, karma-jest)
- add some tests
- showcase how to run the tests

**Comment by johnjacobkenny** [comment]
I have created a simple code here, could you please take a look
https://github.com/johnjacobkenny/karma-jest-example

**Pull request closed without merging**
